apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      labels:
        app: cloud
    spec:
      containers:
        - name: container1
          image: us-central1-docker.pkg.dev/cloud-427713/cloud-repo/container1:latest
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: rahul-pv-dir
              mountPath: /rahul_PV_dir
        - name: container2
          image: us-central1-docker.pkg.dev/cloud-427713/cloud-repo/container2:latest
          ports:
            - containerPort: 6001
          volumeMounts:
            - name: rahul-pv-dir
              mountPath: /rahul_PV_dir
      volumes:
        - name: rahul-pv-dir
          persistentVolumeClaim:
            claimName: task-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: container1
spec:
  type: LoadBalancer
  selector:
    app: cloud
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000

---

apiVersion: v1
kind: Service
metadata:
  name: container2
spec:
  selector:
    app: cloud
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
