name: assignment1
services:
  container1:
    image: "rahulh300/container1"
    ports:
      - "6000:6000"
    container_name: container1
    volumes:
      - ./:/volume
  container2:
    image: "rahulh300/container2"
    ports:
      - "6001:6001"
    container_name: container2
    volumes:
      - ./:/volume
    networks:
      default:
          aliases:
              - container2