name: assignment1
services:
  container1:
    image: "rahulh300/container1"
    ports:
      - "6000:6000"
    container_name: container1
  container2:
    image: "rahulh300/container2"
    ports:
      - "7000:7000"
    container_name: container2
    volumes:
      - ./:/volume
    networks:
      default:
          aliases:
              - container2