services:
  container1:
    image: "rahulh300/container1"
    ports:
      - "6000:6000"
    volumes:
      - ./:/volume
    networks:
      - csci5409-a1
  container2:
    image: "rahulh300/container2"
    ports:
      - "6001:6001"
    volumes:
      - ./:/volume
    networks:
      - csci5409-a1
    
networks:
  csci5409-a1:
    driver: bridge